<?php
namespace app\admin\controller;
//header("content-type:text/html;charset=utf-8");

use think\Controller;
use think\Request;
use think\Db;
use app\model\PortalUrl;
use app\service\FileService;

class A extends Controller
{

    private $fileService;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->fileService=new FileService();
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function j(Request $request)
    {
        //获取之后的路径
        $url=key($request->param());
        $param=ltrim($url,'/admin/a/j/');
        $param=substr($param,0,strpos($param,'_')?:strlen($param));//strpos('_',$param)?

        $portal = PortalUrl::where('localpath', $param)->where('isuse', 1)->field('id,pid')->with([
            'project' => function ($project) {
                $project->field('id,jumptype');
            }
        ])->select()[0];

        if($portal) {
            $jumptype = $portal['project'][0]['jumptype'];
            $projectid = $portal['project'][0]['id'];

            //randomtype替换对应的字符串
            $urls = $this->fileService->getJumpUrls($jumptype, $projectid);
            $skipstr = $this->fileService->sikpsort($jumptype, $urls);
            $his = $this->fileService->addhitstr($portal['id']);
            $randomStr = $his . $skipstr;


            $this->assign('random', $randomStr);
            return $this->fetch('model');
        }else{
            return ('网页被禁止或被检测');
        }
    }


    //添加点击量
    public function hit()
    {
        $id=input('post.id');
        if($id) {
            Db::name('portal_url')->where('id', $id)->setInc('hit', 1);
        }
        return $id;
    }

}
