<?php

namespace app\admin\controller;

use think\Controller;
use think\Request;
use app\model\Project;
use app\model\OwnUrl;
use app\service\WechatService;
use app\util\Email;
use app\util\Curl;

class Test extends Controller
{

    private $wechatServer;
    private $curl;
    private $email;
    private $access_token;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->wechatServer=new WechatService();
        $this->curl=new Curl();
        $this->email=new Email;
        $this->access_token=$this->wechatServer->getAccessToken();
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {

        $urls=request()->param();

        $data=$this->curl->curlRequest('http://weixin.mudaxi.com/admin/index/index');

        $body=json_decode($data['data'],true)['urls'];

        dump($body);

    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
